---

#Override default image
#aws_image: "{{ aws_image}}"

#   Cloud Formation Stack Name
stack_name: "myansibleservers"

# SSH Keypair for the instance
aws_key_name: "ansible-key"

#Establish server hostname
server_name: "server01.norahs-eac.com"
server_name2: "server02.norahs-eac.com"

#Type of AWS instance
aws_instancetype: "t2.medium"

# Establish EBS Encryption key
ebs_key: "178e6f0c-66df-4d24-b790-7fcfb1420c01"

#Disks to attach to instance
disks:
  - name: "root_volume"
    type: "gp2"
    size: "100"
    device_name: "/dev/sda1"


